# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_id', models.IntegerField()),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('picture', models.CharField(max_length=200, verbose_name='Картинка')),
                ('info', models.CharField(max_length=200, verbose_name='Информация')),
                ('godnost', models.CharField(max_length=200, verbose_name='Годность')),
                ('add_time', models.DateTimeField(verbose_name='Time product added')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=200, verbose_name='Название секций')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Section'),
        ),
    ]
