# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.ImageField(max_length=200, upload_to='', verbose_name='Картинка'),
        ),
    ]
