# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170330_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='win_id',
        ),
        migrations.AlterField(
            model_name='products',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time product added'),
        ),
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.ImageField(max_length=200, upload_to='/static/app/images/products/', verbose_name='Картинка'),
        ),
    ]
